const mongoose = require('mongoose');

const staffSchema = new mongoose.Schema({
  staffCode: String,
  firstName: String,
  lastName: String,
  email: String,
  phone: String,
  birthday: String,
  gender: String,
  workplace: String,
  status: String,
  jobPosition: String,
  academicLevel: String,
  hourlyRate: Number,
  domicile: String,
  maritalStatus: String,
  currentAddress: String,
  nation: String,
  placeOfBirth: String,
  religion: String,
  citizenId: String,
  dateOfIssue: String,
  placeOfIssue: String,
  resident: String,
  bankAccountNumber: String,
  bankAccountName: String,
  bankName: String,
  personalTaxCode: String,
  role: String,
  emailSignature: String,
  linkedin: String,
  facebook: String,
  skype: String,
  epfNo: String,
  socialSecurityNo: String,
  twilioPhone: String,
  twilioWhatsapp: String,
  password: String,
});

module.exports = mongoose.model('Staff', staffSchema);
